name = "Generative"
uuid = "f7bbe613-faaf-44f4-a459-6f05297601ae"
authors = ["hongbinren <hongbinrenscu@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[targets]
test = ["Test"]
